version: '2'
services:
    tafgescom-app:
        image: tafgescom
        external_links:
            - tafgescom-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/tafgescom
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tafgescom-postgresql:
        extends:
            file: postgresql.yml
            service: tafgescom-postgresql
